### ISSUE TITLE
Stick to markdown best practices

### ISSUE THREAD

**Issue by trivialkettle** [ms1963/TechnicalDebtRecords#2]
Hi,
The markdown exporter does not follow the heading best practices described here: https://www.markdownguide.org/basic-syntax/#heading-best-practices

> You should also put blank lines before and after a heading for compatibility.

Any reason for this?

**Comment by ms1963** [comment]
Dear trivialkettle,I was not aware of these issues. Thank you for pointing me to the URL. I will read the guidelines and provide a mapping without these problems. Unfortunately, I couldn‘t find a high quality Go package to programmatically create Markdown. So I handcrafted the code myself.Kind Regards     MichaelAm 14.10.2024 um 15:51 schrieb trivialkettle ***@***.***>:﻿
Hi,
The markdown exporter does not follow the heading best practices described here: https://www.markdownguide.org/basic-syntax/#heading-best-practices

You should also put blank lines before and after a heading for compatibility.

Any reason for this?

**Comment by trivialkettle** [comment]
Hi,
I created a PR: https://github.com/ms1963/TechnicalDebtRecords/pull/3

**Comment by ms1963** [comment]
Thank you so much for your support.
